export enum ConfigKeys {
  GOOGLE_AUTH = 'GOOGLE_AUTH',
  GOOGLE_SHEET_ID = 'GOOGLE_SHEET_ID',

  BANK_CSAS_WEB_API_KEY = 'BANK_CSAS_WEB_API_KEY',
  BANK_CSAS_REFRESH_TOKEN = 'BANK_CSAS_REFRESH_TOKEN',
  BANK_CSAS_CLIENT_ID = 'BANK_CSAS_CLIENT_ID',
  BANK_CSAS_CLIENT_SECRET = 'BANK_CSAS_CLIENT_SECRET',
}
